name: CI

on: [ push, pull_request ]

env:
  ACTIONS_ALLOW_UNSECURE_COMMANDS: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2.3.4

    - name: Install Node v14
      uses: actions/setup-node@v1.4.4
      with:
        node-version: 14

    - name: deps cache
      uses: actions/cache@v2.1.3
      with:
        path: node_modules/
        key: ${{ runner.os }}-yarn

    - name: install dependencies
      run: sudo yarn

    - name: run tsc
      run: |
        sudo yarn global add typescript
        tsc

    - name: upload build files
      uses: actions/upload-artifact@v2
      with:
        name: tsc-build
        path: build/

  lint:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2.3.4

    - name: Install Node v14
      uses: actions/setup-node@v1.4.4
      with:
        node-version: 14

    - name: download build files
      uses: actions/download-artifact@v2
      with:
        name: tsc-build
        path: build/

    - name: run eslint
      run: |
        sudo yarn global add eslint
        eslint $GITHUB_WORKSPACE/build/**/*.js
